[{"countryName":"Afghanistan"},
{"countryName":"Albania"},
{"countryName":"American Samoa"},
{"countryName":"Argentina"},
{"countryName":"Armenia"},
{"countryName":"Australia"},
{"countryName":"Austria"},
{"countryName":"Azerbaijan"},
{"countryName":"Bahrain"},
{"countryName":"Belarus"},
{"countryName":"Belgium"},
{"countryName":"Bolivia"},
{"countryName":"Brazil"},
{"countryName":"Bulgaria"},
{"countryName":"Canada"},
{"countryName":"Caribbean Islands"},
{"countryName":"Ceylon (Sri Lanka)"},
{"countryName":"Chile"},
{"countryName":"China"},
{"countryName":"Colombia"},
{"countryName":"Costa Rica"},
{"countryName":"Croatia"},
{"countryName":"Cuba"},
{"countryName":"Cyprus"},
{"countryName":"Czech Republic"},
{"countryName":"Denmark"},
{"countryName":"Dominican Republic"},
{"countryName":"Dutch East Indies"},
{"countryName":"Ecuador"},
{"countryName":"Egypt"},
{"countryName":"El Salvador"},
{"countryName":"Estonia"},
{"countryName":"Ethiopia"},
{"countryName":"Fiji"},
{"countryName":"Finland"},
{"countryName":"France"},
{"countryName":"Georgia"},
{"countryName":"Germany"},
{"countryName":"Gibraltar"},
{"countryName":"Greece"},
{"countryName":"Guatemala"},
{"countryName":"Guernsey"},
{"countryName":"Haiti"},
{"countryName":"Honduras"},
{"countryName":"Hong Kong"},
{"countryName":"Hungary"},
{"countryName":"Iceland"},
{"countryName":"Indonesia"},
{"countryName":"Iran"},
{"countryName":"Iraq"},
{"countryName":"Ireland"},
{"countryName":"Isle of Man"},
{"countryName":"Italy"},
{"countryName":"Japan"},
{"countryName":"Jersey"},
{"countryName":"Korea"},
{"countryName":"Laos"},
{"countryName":"Latvia"},
{"countryName":"Lebanon"},
{"countryName":"Liberia"},
{"countryName":"Liechtenstein"},
{"countryName":"Lithuania"},
{"countryName":"Luxembourg"},
{"countryName":"Malaya"},
{"countryName":"Malta"},
{"countryName":"Manchukuo"},
{"countryName":"Mexico"},
{"countryName":"Monaco"},
{"countryName":"Mongolia"},
{"countryName":"Morocco"},
{"countryName":"Nauru"},
{"countryName":"Nepal"},
{"countryName":"Netherlands"},
{"countryName":"Newfoundland"},
{"countryName":"New Zealand"},
{"countryName":"Nicaragua"},
{"countryName":"Northern Rhodesia"},
{"countryName":"Norway"},
{"countryName":"Oman"},
{"countryName":"Palestine"},
{"countryName":"Panama"},
{"countryName":"Paraguay"},
{"countryName":"Peru"},
{"countryName":"Philippines"},
{"countryName":"Poland"},
{"countryName":"Portugal"},
{"countryName":"Portuguese Macau"},
{"countryName":"Portuguese Timor"},
{"countryName":"Romania"},
{"countryName":"Samoa"},
{"countryName":"San Marino"},
{"countryName":"Saudi Arabia"},
{"countryName":"Singapore"},
{"countryName":"Slovakia"},
{"countryName":"South Africa"},
{"countryName":"Southern Rhodesia"},
{"countryName":"Soviet Union"},
{"countryName":"Spain"},
{"countryName":"Sweden"},
{"countryName":"Switzerland"},
{"countryName":"Syria"},
{"countryName":"Thailand"},
{"countryName":"Tonga"},
{"countryName":"Transjordan"},
{"countryName":"Turkey"},
{"countryName":"United Kingdom"},
{"countryName":"United States of America"},
{"countryName":"Uruguay"},
{"countryName":"Vatican City"},
{"countryName":"Venezuela"},
{"countryName":"Yemen"},
{"countryName":"Yugoslavia"}]